Update to `dusk-poseidon` `0.23`
dusk-network/phoenix-core pull request #103
Opened 2021-12-27 11:39 UTC by vlopes11

Resolves #102

2021-12-28 08:17 UTC, herr-seppia approved these changes
LGTM

2021-12-28 14:23 UTC, ZER0 requested changes

2021-12-29 08:08 UTC, herr-seppia approved these changes

2021-12-29 12:45 UTC, ZER0 approved these changes

2021-12-29 12:47 UTC, merged